blank_issues_enabled: false
contact_links:
  - name: Khulnasoft assistance
    url: https://console.khulnasoft.com/support/tickets/
    about: Contact Khulnasoft Assistance for help with product-related issues.